<#
build-and-run.ps1

Automates building the raw-spooler helper and starting the local print agent for testing.
Run this in an elevated PowerShell if you need to install system components.
#>

set-PSDebug -Strict

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$rawDir = Join-Path $scriptDir 'raw-spooler'
$publishDir = Join-Path $rawDir 'publish'

Write-Host "Working dir: $scriptDir"

# Check for dotnet
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    Write-Warning "dotnet CLI not found on PATH. You must install .NET SDK to build raw-spooler."
    Write-Host "Download: https://dotnet.microsoft.com/en-us/download"
    $buildRaw = Read-Host "dotnet not found. Skip building raw-spooler? (y/N)"
    if ($buildRaw -ne 'y' -and $buildRaw -ne 'Y') {
        Write-Host "Aborting. Install .NET SDK then re-run this script."
        exit 1
    }
} else {
    Write-Host "Building raw-spooler (publish)..."
    Push-Location $rawDir
    dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish
    $pubExe = Join-Path $publishDir 'raw-spooler.exe'
    if (Test-Path $pubExe) {
        Write-Host "raw-spooler built: $pubExe"
    } else {
        Write-Warning "raw-spooler executable not found after publish. You can still continue and use PowerShell Out-Printer fallback."
    }
    Pop-Location
}

# Prompt for runtime values
$token = Read-Host "PRINT_AGENT_TOKEN (paste the plaintext token generated by the backend)"
if (-not $token) { Write-Error "PRINT_AGENT_TOKEN is required"; exit 1 }

$storeIds = Read-Host "STORE_IDS (comma-separated store UUIDs)"
if (-not $storeIds) { Write-Error "STORE_IDS is required"; exit 1 }

$printerInterface = Read-Host "PRINTER_INTERFACE (e.g. printer:Print iD). Leave empty to use agent default"
if (-not $printerInterface) { $printerInterface = '' }

$dryRunAnswer = Read-Host "DRY_RUN? Enter 0 for real printing, 1 for dry-run (default 0)"
if ($dryRunAnswer -eq '') { $dryRunAnswer = '0' }

# Start discovery helper in separate PowerShell window
$discoverCmd = "node `"$scriptDir\printer-http.cjs`""
Start-Process -FilePath "powershell.exe" -ArgumentList "-NoExit","-Command",$discoverCmd -WorkingDirectory $scriptDir
Write-Host "Started printer discovery helper in a new PowerShell window."

Start-Sleep -Seconds 1

# Build command to start agent with environment variables set inside the new shell
$agentCmd = "Set-Item -Path Env:PRINT_AGENT_TOKEN -Value \"$token\"; `\n"
$agentCmd += "Set-Item -Path Env:STORE_IDS -Value \"$storeIds\"; `\n"
if ($printerInterface -ne '') { $agentCmd += "Set-Item -Path Env:PRINTER_INTERFACE -Value \"$printerInterface\"; `\n" }
$agentCmd += "Set-Item -Path Env:DRY_RUN -Value \"$dryRunAnswer\"; `\n"
$agentCmd += "Write-Host \"Starting agent (PRINT_AGENT_TOKEN set, DRY_RUN=$dryRunAnswer)...\"; `\n"
$agentCmd += "node `"$scriptDir\index.js`""

Start-Process -FilePath "powershell.exe" -ArgumentList "-NoExit","-Command",$agentCmd -WorkingDirectory $scriptDir
Write-Host "Started delivery-print-agent in a new PowerShell window."

Write-Host "\nNow open the frontend Printer Setup UI, select or input the printer (use the exact Windows printer name), set Printer Type to EPSON, uncheck DRY_RUN and click 'Testar impressão'."
Write-Host "Logs and generated files are available under: $scriptDir\logs and $scriptDir\failed-print\"

Write-Host "Done."